### ISSUE TITLE
Error: Cannot find module 'commander'

### ISSUE THREAD

**Issue by noahvogt** [lxhom/neofile#1]
### what I ran
So this error came up when running `$ node neofile.js` to start the program. This is the full error output:

```
node:internal/modules/cjs/loader:927
  throw err;
  ^

Error: Cannot find module 'commander'
Require stack:
- /home/noah/dox/dev/neofile/neofile.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:924:15)
    at Function.Module._load (node:internal/modules/cjs/loader:769:27)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at main (/home/noah/dox/dev/neofile/neofile.js:8:23)
    at Object.<anonymous> (/home/noah/dox/dev/neofile/neofile.js:134:1)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/noah/dox/dev/neofile/neofile.js' ]
}
```

### what solved the issue
`$ npm i -g` didn't help either. So I thought manually installing would fix it, so I ran `# npm install commander -g`. But the error was somehow resolved by reinstalling sails as proposed [on this SO thread](https://stackoverflow.com/questions/49393301/error-cannot-find-module-commander).

    npm uninstall sails -g
    sudo npm install sails -g

### why make an issue that I fixed already?
So I have never coded something in NodeJS, but I really like the idea of this project and hope development will succeed, so I could may use it. Maybe this error could be common when non-JS people try to run this on their machine. *So maybe this will be helpful because of that.*

**Comment by lxhom** [comment]
Found the issue. The problem wasn't on your end, its my fault because I somehow managed to install the commander module without adding it to the package (the dependancy isn't in package.json). I'm already working on a fix, so it should work soon ^^

**Comment by lxhom** [comment]
Update: [This commit](https://github.com/lxhom/neofile/commit/5abb016d9a279f3e83ae73dd4de0739bbcd018f7) should fix it, commander is now in the dependancies in package.json.

**Comment by noahvogt** [comment]
Nice, I will test it out soon.
